global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['daily-v2-test-greenfield.service.nimbus.example']
    metrics_path: /prometheus/metrics
    scheme: https
    authorization:
      type: Bearer
      credentials_file: api_key.txt
