FROM grafana/grafana:10.4.0

ENV GF_AUTH_ANONYMOUS_ENABLED=true
ENV GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
ENV GF_AUTH_DISABLE_LOGIN_FORM=true
ENV GF_SERVER_HTTP_PORT=3001
ENV GF_INSTALL_PLUGINS=grafana-pyroscope-app

COPY grafana-datasources.yaml /etc/grafana/provisioning/datasources/datasources.yaml
COPY grafana-dashboards.yaml /etc/grafana/provisioning/dashboards/dashboards.yaml
COPY dashboards/ /var/lib/grafana/dashboards/

EXPOSE 3001
