version: 2

models:

  - name: table
    description: description

    config:
      materialized: table
      tags:
        - base

    columns:
      - name: column_name
        data_type: text
        data_tests:
          - not_null
